package br.com.ucsal.chatbot.user.windows;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


import br.com.ucsal.chatbot.user.controller.ApoiarChamadoBO;
import br.com.ucsal.chatbot.user.controller.CancelarChamadoBO;
import br.com.ucsal.chatbot.user.controller.PesquisarChamadoBO;
import br.com.ucsal.chatbot.user.controller.ReabrirChamadoBO;
import br.com.ucsal.chatbot.user.model.Chamado;
import br.com.ucsal.chatbot.user.view.MensagemInterface;


/*
 * Essa classe pode ser invocada pelas classes "Tela_PesquisarChamadoPor" 
 * e "Tela_ListaChamado".
 * Para saber quem fez a invocação é utilizada a variavel 
 * "int direcionamento", onde:
 * 0 - Invocação feita pela classe Tela_PesquisarChamadoPor
 * 1 - Invocação feita pela classe Tela_ListaChamado
 * Caso a invocação tenha passado pela classe Tela_ChamadoSemelhante, 
 * ao clicar no botão "buttonApoiarChamado", o usuário deve ser 
 * redirecionado para Tela_Final. Também não é possível cancelar o chamado, 
 * botão "buttonCancelarChamado" fica com Enabled = false.
 * */
public class Tela_DetalhesChamado extends javax.swing.JFrame {
	Connection conexao = Tela_Home.getConnection();
	static int codigoChamado = 1000;
	
	//Criando um objeto com as informações do chamado
	Chamado c = PesquisarChamadoBO.pesquisarChamado(codigoChamado, conexao);
	static int direcionamento = 0;
	static int direcionamento2 = 0;
	
	public static void setCodigoChamado(int c) {
		codigoChamado = c;
	}
	public static void setDirecionamento(int d) {
		direcionamento = d;
	}
	
	public static void setDirecionamento2(int d) {
		direcionamento2 = d;
	}
	
	

    /**
     * Creates new form NewJFrame
     * @throws SQLException 
     */
    public Tela_DetalhesChamado() throws SQLException {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws SQLException {

        panelPrincipal = new javax.swing.JPanel();
        panelConteudo = new javax.swing.JPanel();
        buttonReabrirChamado = new javax.swing.JButton();
        buttonCancelarChamado = new javax.swing.JButton();
        labelNumeroChamado1 = new javax.swing.JLabel();
        textTituloChamado = new javax.swing.JTextArea();
        labelDataHoraChamado = new javax.swing.JLabel();
        labelLocal = new javax.swing.JLabel();
        labelLocalVariavel = new javax.swing.JLabel();
        labelResponsavel = new javax.swing.JLabel();
        labelResponsavelVariavel = new javax.swing.JLabel();
        textDescricaoVariavel = new javax.swing.JTextArea();
        labelApoiadores = new javax.swing.JLabel();
        buttonApoiarChamado = new javax.swing.JButton();
        labelDescricao = new javax.swing.JLabel();
        buttonVoltar = new javax.swing.JButton();
        panelCabecalho = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        labelStatus = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HelpDesk Chatbot");

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(720, 400));

        panelConteudo.setBackground(new java.awt.Color(255, 255, 255));
        panelConteudo.setAlignmentX(1.0F);
        panelConteudo.setPreferredSize(new java.awt.Dimension(400, 720));

        buttonReabrirChamado.setBackground(new java.awt.Color(255, 255, 255));
        buttonReabrirChamado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonReabrirChamado.setText("Reabrir chamado");
        buttonReabrirChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonReabrirChamadoActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        buttonCancelarChamado.setBackground(new java.awt.Color(255, 255, 255));
        buttonCancelarChamado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonCancelarChamado.setText("Cancelar chamado");
        buttonCancelarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonCancelarChamadoActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        labelNumeroChamado1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelNumeroChamado1.setText("4111");

        textTituloChamado.setEditable(false);
        textTituloChamado.setColumns(20);
        textTituloChamado.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        textTituloChamado.setRows(5);
        textTituloChamado.setText("Texto");
        textTituloChamado.setBorder(null);

        labelDataHoraChamado.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        labelDataHoraChamado.setForeground(new java.awt.Color(153, 153, 153));
        labelDataHoraChamado.setText("Chamado aberto em 23/11/1998 ás 13:00");

        labelLocal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelLocal.setText("Local:");

        labelLocalVariavel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelLocalVariavel.setText("Nome");

        labelResponsavel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelResponsavel.setText("Responsável:");

        labelResponsavelVariavel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelResponsavelVariavel.setText("Nome");

        textDescricaoVariavel.setEditable(false);
        textDescricaoVariavel.setColumns(20);
        textDescricaoVariavel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textDescricaoVariavel.setRows(5);
        textDescricaoVariavel.setText("Descrição");
        textDescricaoVariavel.setBorder(null);

        labelApoiadores.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelApoiadores.setText("Existem 100 pessoass apoiando a resolução desse chamado.");

        buttonApoiarChamado.setBackground(new java.awt.Color(0, 204, 51));
        buttonApoiarChamado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonApoiarChamado.setForeground(new java.awt.Color(255, 255, 255));
        buttonApoiarChamado.setText("Apoiar chamado!");
        buttonApoiarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonApoiarChamadoActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        labelDescricao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelDescricao.setText("Descrição:");

        buttonVoltar.setBackground(new java.awt.Color(0, 204, 255));
        buttonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonVoltarActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout panelConteudoLayout = new javax.swing.GroupLayout(panelConteudo);
        panelConteudo.setLayout(panelConteudoLayout);
        panelConteudoLayout.setHorizontalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelConteudoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelApoiadores, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConteudoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConteudoLayout.createSequentialGroup()
                                .addComponent(labelResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelResponsavelVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23))
                            .addGroup(panelConteudoLayout.createSequentialGroup()
                                .addComponent(labelLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLocalVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
                            .addGroup(panelConteudoLayout.createSequentialGroup()
                                .addComponent(labelNumeroChamado1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textTituloChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(panelConteudoLayout.createSequentialGroup()
                                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelConteudoLayout.createSequentialGroup()
                                        .addComponent(textDescricaoVariavel)
                                        .addGap(8, 8, 8))
                                    .addComponent(labelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))))
                    .addGroup(panelConteudoLayout.createSequentialGroup()
                        .addComponent(buttonVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDataHoraChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConteudoLayout.createSequentialGroup()
                        .addComponent(buttonApoiarChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonReabrirChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCancelarChamado))
                        .addGap(30, 30, 30)))
                .addGap(1, 1, 1))
        );
        panelConteudoLayout.setVerticalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataHoraChamado)
                    .addComponent(buttonVoltar))
                .addGap(20, 20, 20)
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConteudoLayout.createSequentialGroup()
                        .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTituloChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumeroChamado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLocalVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelResponsavelVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(labelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDescricaoVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelApoiadores, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(buttonReabrirChamado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelarChamado))
                    .addComponent(buttonApoiarChamado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        textDescricaoVariavel.getAccessibleContext().setAccessibleParent(panelConteudo);

        panelCabecalho.setBackground(new java.awt.Color(0, 204, 255));
        panelCabecalho.setForeground(new java.awt.Color(0, 204, 255));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("ChatBot");

        labelStatus.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("online");

        javax.swing.GroupLayout panelCabecalhoLayout = new javax.swing.GroupLayout(panelCabecalho);
        panelCabecalho.setLayout(panelCabecalhoLayout);
        panelCabecalhoLayout.setHorizontalGroup(
            panelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabecalhoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCabecalhoLayout.setVerticalGroup(
            panelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        
        
        /*
         * Sempre que uma alteração for realizada é invocado esse método para
         * fazer a atualização do status.
         * */
        atualizarStatus();
        
        
        
        pack();
        setLocationRelativeTo(null);
        
    }// </editor-fold>                        

    private void buttonReabrirChamadoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                                     
       
    	//Reabre o chamado e atualiza o status do objeto
    	ReabrirChamadoBO.reabrirChamado(codigoChamado, conexao);
        atualizarStatus();
    }                                                    

    private void buttonCancelarChamadoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                                      
       
    	//Cancela o chamado e atualiza o status do objeto
    	CancelarChamadoBO.cancelarChamado(codigoChamado, conexao);
        atualizarStatus();
    }                                                     

    private void buttonApoiarChamadoActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                                    
       
    	//Apoia o chamado e atualiza o status do objeto
    	ApoiarChamadoBO.apoiarChamado(codigoChamado, conexao);
        atualizarStatus();
        
        //Muda o texto do botão e desabilita ele
    	buttonApoiarChamado.setText("Apoiado!");
        buttonApoiarChamado.setEnabled(false);
        
        /*
         * Caso a invocação do metódo tenha passado pela 
         * classe Tela_ChamadoSemelhante deverá ser feito o redirecionamento
         * para a tela final da aplicação
         * */
        if(direcionamento == 1) {
        	this.dispose();
        	new Tela_Final("Chamado apoiado!").main(null);
        }
        
    }                                                   

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                             
      
    	//Redireciona de volta para tela de pesquisar chamado
    	if(direcionamento2 == 1) {
    		this.dispose();
    		new Tela_ListaChamados().main(null);
    	  
       }else {
    	 //Redireciona de volta para tela de lista de chamados
    	   this.dispose();
    	   new Tela_PesquisarChamadoPor().main(null);
       }
    }
    
    
    /*
     * Metódo invocado sempre que é necessário atualizar informações do
     * chamado
     * */
    public void atualizarStatus() throws SQLException {
    	
    	c = PesquisarChamadoBO.pesquisarChamado(codigoChamado, conexao);
    	labelDataHoraChamado.setText("Chamado aberto " + c.getData_abertura() + " as " + c.getHora_abertura() + ".");
        labelNumeroChamado1.setText(String.valueOf(c.getCod_chamado()));
        textTituloChamado.setText(MensagemInterface.formatarTexto35(c.getAssunto() + " (" + c.getStatus() +")"));
        labelLocalVariavel.setText(c.getSala());
        labelResponsavelVariavel.setText(c.getResponsavel());
        textDescricaoVariavel.setText(MensagemInterface.formatarTexto60(c.getDescricao()));
        labelApoiadores.setText("Existe(m) " + c.getCont_apoio() + " pessoa(s) apoiando a resolução do chamado");
        
        /*
         * Caso o chamado esteja inativo, é apenas exibido o botão 
         * para reativá-lo.
         * */
        if(c.getStatus().equalsIgnoreCase("CANCELADO") || c.getStatus().equalsIgnoreCase("RESOLVIDO")) {
        	buttonCancelarChamado.setVisible(false);
        	buttonReabrirChamado.setVisible(true);
        	buttonApoiarChamado.setEnabled(false);
        }else {
        	/*
             * Caso o chamado esteja ativo, é exibido o botão 
             * para desativá-lo e apoiá-lo.
             * */
        	buttonReabrirChamado.setVisible(false);
        	buttonCancelarChamado.setVisible(true);
        	buttonApoiarChamado.setEnabled(true);
        }
        
        /*
         * Caso a invocação tenha passado pela classe Tela_ChamadoSemelhante
         * deve-se desabilitar os botões
         * "buttoReabirChamado" e "buttonCancelarChamado" 
         * */
        if(direcionamento == 1) {
        	buttonReabrirChamado.setEnabled(false);
        	buttonCancelarChamado.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_DetalhesChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_DetalhesChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_DetalhesChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_DetalhesChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new Tela_DetalhesChamado().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonApoiarChamado;
    private javax.swing.JButton buttonCancelarChamado;
    private javax.swing.JButton buttonReabrirChamado;
    private javax.swing.JButton buttonVoltar;
    private java.awt.Label label1;
    private javax.swing.JLabel labelApoiadores;
    private javax.swing.JLabel labelDataHoraChamado;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelLocal;
    private javax.swing.JLabel labelLocalVariavel;
    private javax.swing.JLabel labelNumeroChamado1;
    private javax.swing.JLabel labelResponsavel;
    private javax.swing.JLabel labelResponsavelVariavel;
    private java.awt.Label labelStatus;
    private javax.swing.JPanel panelCabecalho;
    private javax.swing.JPanel panelConteudo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea textDescricaoVariavel;
    private javax.swing.JTextArea textTituloChamado;
    // End of variables declaration                   
}
