package br.com.ucsal.chatbot.user.windows;

import java.sql.Connection;
import java.sql.SQLException;

import br.com.ucsal.chatbot.user.exception.CampoContemLetra;
import br.com.ucsal.chatbot.user.exception.CampoObrigatorioVazio;
import br.com.ucsal.chatbot.user.exception.SalaNaoExiste;
import br.com.ucsal.chatbot.user.util.Validador;
import br.com.ucsal.chatbot.user.view.MensagemInterface;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Sakura
 */
public class Tela_Sala extends javax.swing.JFrame {
	Connection conexao = Tela_Home.getConnection();
	static String salaContexto = "B401";
	static int direcionamento = 0;
	
	public static void setDirecionamento(int num) {
		direcionamento = num;
	}
	
	public static String getSala() {
		return salaContexto;
	}

    /**
     * Creates new form NewJFrame
     */
    public Tela_Sala() {
    	this.conexao = conexao;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelConteudo = new javax.swing.JPanel();
        buttonA = new javax.swing.JButton();
        imgBot = new javax.swing.JLabel();
        textMensagem = new javax.swing.JTextArea();
        buttonB = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonD = new javax.swing.JButton();
        buttonE = new javax.swing.JButton();
        buttonCorrigirBloco = new javax.swing.JButton();
        imgBot2 = new javax.swing.JLabel();
        textMensagem2 = new javax.swing.JTextArea();
        textUserMensagem = new javax.swing.JTextField();
        buttonEnviar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        panelCabecalho = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        labelStatus = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HelpDesk Chatbot");

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(720, 400));

        panelConteudo.setBackground(new java.awt.Color(255, 255, 255));
        panelConteudo.setAlignmentX(1.0F);
        panelConteudo.setPreferredSize(new java.awt.Dimension(400, 720));

        buttonA.setBackground(new java.awt.Color(255, 255, 255));
        buttonA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonA.setText("A");
        buttonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAActionPerformed(evt);
            }
        });

        imgBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/small2.png"))); // NOI18N
        imgBot.setText("jLabel1");

        textMensagem.setColumns(20);
        textMensagem.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        textMensagem.setRows(5);
        textMensagem.setText(MensagemInterface.getMensagemBloco());
        textMensagem.setBorder(null);
        textMensagem.setEditable(false);

        buttonB.setBackground(new java.awt.Color(255, 255, 255));
        buttonB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonB.setText("B");
        buttonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBActionPerformed(evt);
            }
        });

        buttonC.setBackground(new java.awt.Color(255, 255, 255));
        buttonC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        buttonD.setBackground(new java.awt.Color(255, 255, 255));
        buttonD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonD.setText("D");
        buttonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDActionPerformed(evt);
            }
        });

        buttonE.setBackground(new java.awt.Color(255, 255, 255));
        buttonE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonE.setText("E");
        buttonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEActionPerformed(evt);
            }
        });

        buttonCorrigirBloco.setBackground(new java.awt.Color(255, 255, 255));
        buttonCorrigirBloco.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonCorrigirBloco.setText("Corrigir");
        buttonCorrigirBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCorrigirBlocoActionPerformed(evt);
            }
        });

        imgBot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/small2.png"))); // NOI18N
        imgBot2.setText("jLabel1");

        textMensagem2.setColumns(20);
        textMensagem2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        textMensagem2.setRows(5);
        textMensagem2.setText(MensagemInterface.getMensagemNumeroSala());
        textMensagem2.setBorder(null);
        textMensagem2.setEditable(false);

        textUserMensagem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textUserMensagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telegram-icone-icon-3.png"))); // NOI18N
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonEnviarActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        buttonVoltar.setBackground(new java.awt.Color(51, 204, 255));
        buttonVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        
        buttonCorrigirBloco.setEnabled(false);
        imgBot2.setVisible(false);
        buttonEnviar.setVisible(false);
        textMensagem2.setVisible(false);
        textUserMensagem.setVisible(false);

        javax.swing.GroupLayout panelConteudoLayout = new javax.swing.GroupLayout(panelConteudo);
        panelConteudo.setLayout(panelConteudoLayout);
        panelConteudoLayout.setHorizontalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConteudoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConteudoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(buttonCorrigirBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConteudoLayout.createSequentialGroup()
                        .addComponent(imgBot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelConteudoLayout.createSequentialGroup()
                            .addComponent(textUserMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelConteudoLayout.createSequentialGroup()
                            .addComponent(imgBot2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(textMensagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(panelConteudoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonE, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonD, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonA, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConteudoLayout.setVerticalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConteudoLayout.createSequentialGroup()
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConteudoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(imgBot, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConteudoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(textMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCorrigirBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBot2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConteudoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(textMensagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUserMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEnviar))
                .addGap(18, 18, 18)
                .addComponent(buttonVoltar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelCabecalho.setBackground(new java.awt.Color(0, 204, 255));
        panelCabecalho.setForeground(new java.awt.Color(0, 204, 255));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("ChatBot");

        labelStatus.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("online");

        javax.swing.GroupLayout panelCabecalhoLayout = new javax.swing.GroupLayout(panelCabecalho);
        panelCabecalho.setLayout(panelCabecalhoLayout);
        panelCabecalhoLayout.setHorizontalGroup(
            panelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabecalhoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCabecalhoLayout.setVerticalGroup(
            panelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void buttonEActionPerformed(java.awt.event.ActionEvent evt) {                                        
        buttonA.setEnabled(false);
        buttonB.setEnabled(false);
        buttonC.setEnabled(false);
        buttonD.setEnabled(false);
        buttonCorrigirBloco.setEnabled(true);
        imgBot2.setVisible(true);
        textUserMensagem.setVisible(true);
        buttonEnviar.setVisible(true);
        textMensagem2.setVisible(true);


    }                                       

    private void buttonDActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	buttonA.setEnabled(false);
        buttonB.setEnabled(false);
        buttonC.setEnabled(false);
        buttonE.setEnabled(false);
        buttonCorrigirBloco.setEnabled(true);
        imgBot2.setVisible(true);
        textUserMensagem.setVisible(true);
        buttonEnviar.setVisible(true);
        textMensagem2.setVisible(true);


    }                                       

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	buttonA.setEnabled(false);
        buttonB.setEnabled(false);
        buttonE.setEnabled(false);
        buttonD.setEnabled(false);
        buttonCorrigirBloco.setEnabled(true);
        imgBot2.setVisible(true);
        textUserMensagem.setVisible(true);
        buttonEnviar.setVisible(true);
        textMensagem2.setVisible(true);

        
    }                                       

    private void buttonBActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	buttonA.setEnabled(false);
        buttonE.setEnabled(false);
        buttonC.setEnabled(false);
        buttonD.setEnabled(false);
        buttonCorrigirBloco.setEnabled(true);
        imgBot2.setVisible(true);
        textUserMensagem.setVisible(true);
        buttonEnviar.setVisible(true);
        textMensagem2.setVisible(true);

    }                                       

    private void buttonAActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	buttonE.setEnabled(false);
        buttonB.setEnabled(false);
        buttonC.setEnabled(false);
        buttonD.setEnabled(false);
        buttonCorrigirBloco.setEnabled(true);
        imgBot2.setVisible(true);
        textUserMensagem.setVisible(true);
        buttonEnviar.setVisible(true);
        textMensagem2.setVisible(true);

    }                                       

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                             
    	textUserMensagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,0), 1, true));;
    	String sala = textUserMensagem.getText();
    	
    	if(!textUserMensagem.getText().equals("")) {
    		if(Validador.letraCheck(sala)) {
        		if(buttonA.isEnabled()) {
            		sala = "A" + sala;
            	}else if(buttonB.isEnabled()) {
            		sala = "B" + sala;
            	} else if(buttonC.isEnabled()) {
            		sala = "C" + sala;
            	} else if(buttonD.isEnabled()) {
            		sala = "D" + sala;
            	} else if(buttonE.isEnabled()) {
            		sala = "E" + sala;
            	}
            		
            	
            	if(Validador.checarSala(sala, conexao)) {
            		salaContexto = sala;
            		this.dispose();
            		
            		if(direcionamento == 0) {
            			new Tela_Equipamento().main(null);
            		}else {
            			new Tela_DetalhesChamado().setDirecionamento(0);
            			
            			this.dispose();
            	    	new Tela_ListaChamados().main(null);
            		}
            		
            	} else {
            		String aux = MensagemInterface.formatarTexto36(new SalaNaoExiste().SalaNaoExisteInterface());
            		textMensagem2.setText(MensagemInterface.getMensagemNumeroSala() + "\n" + aux);
            		textUserMensagem.setText("");
            	}
        	}else {
        		textMensagem2.setText(MensagemInterface.getMensagemNumeroSala() + "\n" + MensagemInterface.formatarTexto36(CampoContemLetra.CampoContemLetra()));
        	}
    	}else {
    		textUserMensagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,0,51), 3, true));
    		textMensagem2.setText(MensagemInterface.getMensagemNumeroSala() + "\n" + MensagemInterface.formatarTexto36(CampoObrigatorioVazio.CampoObrigatorioVazio()));
    	}
    	
    	
    }                                            

    private void buttonCorrigirBlocoActionPerformed(java.awt.event.ActionEvent evt) {                                                    
    	buttonA.setEnabled(true);
        buttonB.setEnabled(true);
        buttonC.setEnabled(true);
        buttonD.setEnabled(true);
        buttonE.setEnabled(true);
        buttonCorrigirBloco.setVisible(true);
        imgBot2.setVisible(false);
        buttonEnviar.setVisible(false);
        textMensagem2.setVisible(false);
        textUserMensagem.setVisible(false);
        textMensagem2.setText(MensagemInterface.getMensagemNumeroSala());
    }                                                                                     

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	this.dispose();
        if(direcionamento == 0) {
        	new Tela_Home().main(null);
        }else {
        	new Tela_PesquisarChamadoPor().main(null);
        }
       
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Sala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonA;
    private javax.swing.JButton buttonB;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonCorrigirBloco;
    private javax.swing.JButton buttonD;
    private javax.swing.JButton buttonE;
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel imgBot;
    private javax.swing.JLabel imgBot2;
    private java.awt.Label label1;
    private java.awt.Label labelStatus;
    private javax.swing.JPanel panelCabecalho;
    private javax.swing.JPanel panelConteudo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea textMensagem;
    private javax.swing.JTextArea textMensagem2;
    private javax.swing.JTextField textUserMensagem;
    // End of variables declaration                   
}
